export default [
  { name: "en_US", title: "English", shortname: "en" },
  { name: "ru_RU", title: "Русский", shortname: "ru" },
  { name: "de_DE", title: "Deutsch", shortname: "de" },
  { name: "zh_CN", title: "中文", shortname: "cn" },
  { name: "es_ES", title: "Español", shortname: "es" },
  { name: "pt_PT", title: "Português", shortname: "pt" },
  { name: "id_ID", title: "Bahasa Indonesia", shortname: "id" },
  { name: "ar_KW", title: "العربية", shortname: "ar" },
  { name: "tr_TR", title: "Türk", shortname: "tr" },
  { name: "it_IT", title: "Italiano", shortname: "it" },
  { name: "ko_KO", title: "한국어", shortname: "ko" },
  { name: "fr_FR", title: "Français", shortname: "fr" },
  { name: "th_TH", title: "ไทย", shortname: "th" },
  { name: "vi_VN", title: "Tiếng việt", shortname: "vi" },
  { name: "ms_MY", title: "Bahasa Melayu", shortname: "my" },
  { name: "hi_IN", title: "हिंदी", shortname: "hi" },
  { name: "ph_PH", title: "Filipino", shortname: "ph" },
  { name: "bn_IN", title: "বাঙালি", shortname: "bn" }
];
